framework:
  messenger:
    serializer:
      default_serializer: messenger.transport.symfony_serializer
      symfony_serializer:
        format: json
        context: { }

    transports:
      amqp:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange: { type: direct }
          auto_setup: false

    routing:
      App\StoreCustomer: amqp
      App\CustomerStored: amqp
