framework:
  messenger:
    serializer:
      default_serializer: messenger.transport.symfony_serializer
      symfony_serializer:
        format: json
        context: { }

    transports:
      amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      App\StoreCustomer: amqp
      App\CustomerStored: amqp
