version: "3"

services:

  queue:
    build:
      context: ../docker/rabbitmq
    container_name: comparison-golang-queue
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 2000MiB
      RABBITMQ_ERLANG_COOKIE: f6fAjy5yes
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  db:
    build:
      context: ../docker/postgres
    container_name: comparison-golang-db
    restart: always
    volumes:
      - ../docker/postgres/conf/postgresql.conf:/etc/postgresql.conf
      - ../docker/postgres/data/customers.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: demo
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql.conf

  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    container_name: comparison-golang-consumer
    environment:
      AMQP_CONNECTION: amqp://admin:admin123@queue:5672/
      DB_CONNECTION: host=db port=5432 user=demo password=123456789 dbname=demo sslmode=disable
      DB_CONNECTIONS_COUNT: 250
    command: ["/bin/bash", "-c", "sleep 10 && /bin/prep && /bin/tester"]
    depends_on:
      - db
      - queue