services:

  service_bus.logger.handlers.stdout_handler:
    class: ServiceBus\Infrastructure\Logger\Handlers\StdOut\StdOutHandler

  # Override concurrent tasks count
  ServiceBus\EntryPoint\EntryPoint:
    arguments:
      $transport: '@ServiceBus\Transport\Common\Transport'
      $processor: '@ServiceBus\EntryPoint\EntryPointProcessor'
      $logger: '@service_bus.logger'
      $maxConcurrentTaskCount: 250
      $awaitDelay: 10
