services:
  # Generate PostgreSQL schema for service-bus components
  postgresql_schema_builder:
    class: PostgreSQLSchemaBuilder
    public: true
    arguments:
      $adapter: '@ServiceBus\Storage\Common\DatabaseAdapter'

  service_bus.logger.handlers.stdout_handler:
    class: ServiceBus\Infrastructure\Logger\Handlers\StdOut\StdOutHandler

  #service_bus.logger:
    #class: Monolog\Logger
    #arguments:
      #$name: '%service_bus.entry_point%'
      #$handlers:
        #- '@service_bus.logger.handlers.stdout_handler'

  # Override concurrent tasks count
  ServiceBus\EntryPoint\EntryPoint:
    arguments:
      $transport: '@ServiceBus\Transport\Common\Transport'
      $processor: '@ServiceBus\EntryPoint\EntryPointProcessor'
      $logger: '@service_bus.logger'
      $maxConcurrentTaskCount: 80
      $awaitDelay: 20
